---
    version: "3.8"

    services:
      # A MySQL service as close to production as currently possible
      # To run it as a standalone container:
      #   docker run --name mysql-8.0 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d -p 27017:3306 mysql:8.0
      mysql-8.0:
        image: mysql:8.0
        ports:
          - "3306:3306"
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: psd_cherrytrack_dev
        volumes:
          - mysql-volume:/var/lib/mysql

    volumes:
      mysql-volume:
